#!/bin/busybox sh

mkdir /proc
mkdir /sys
mkdir /mnt
mkdir /nfs

mount -t proc proc proc
mount -t sysfs sys sys
mdev -s

ifconfig eth0 up
udhcpc -i eth0 -s /etc/udhcpc.script

clear
echo "Welcome to the Fast Linux Deployment Toolkit"
echo "Created by Penn Manor School District"
echo "Based upon work by Andrew Lobos <andrew@lobos.me>"

./image.sh
setsid bash -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
